FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements-backend.txt requirements.txt
COPY backend backend

RUN pip install --no-cache-dir -r requirements.txt

#CMD gunicorn --proxy-headers --bind 0.0.0.0:$BACKEND_PORT backend.main:app -k uvicorn.workers.UvicornWorker
CMD fastapi run backend/main.py --host 0.0.0.0 --port $BACKEND_PORT --proxy-headers
