services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: backend
    restart: unless-stopped
    command: uvicorn backend.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    expose:
      - 8000
    environment:
      - PORT=8000
      - MONGO_URI=mongodb+srv://jauriberamirez:jWowycmd2j49a8RU@sr-cluster.ikxkpft.mongodb.net/?retryWrites=true&w=majority&appName=SR-Cluster
    networks:
      - back
    volumes:
      - ./backend:/backend
    env_file: ".env"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    image: frontend
    container_name: frontend
    restart: unless-stopped
    command: python -m streamlit run frontend/main.py
    expose:
      - 8501
    depends_on:
      - backend
    volumes:
      - ./img:/img
      - ./frontend:/frontend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - back
      - nginx
    env_file: ".env"

  nginx-proxy:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - back
      - nginx

networks:
  back:
  nginx:
