FROM python:3.12-slim

COPY .streamlit .streamlit
COPY README.md README.md

COPY requirements-frontend.txt requirements.txt
COPY frontend frontend

RUN pip install --no-cache-dir -r requirements.txt

CMD streamlit run frontend/app.py
