services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: backend
    restart: unless-stopped
    expose:
      - $BACKEND_PORT
    networks:
      - back
    volumes:
      - ./backend:/backend
    env_file: ".env"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    image: frontend
    container_name: frontend
    restart: unless-stopped
    command: python -m streamlit run frontend/main.py
    expose:
      - $FRONTEND_PORT
    depends_on:
      - backend
    volumes:
      - ./img:/img
      - ./frontend:/frontend
    networks:
      - back
      - nginx
    env_file: ".env"

  nginx-proxy:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - back
      - nginx

networks:
  back:
  nginx:
